apiVersion: 2018-10-01
location: centralus
name: alldaydevops
properties:
  containers:
  - name: application
    properties:
      image: alldaydevops.azurecr.io/mlabouardy/application:TAG
      resources:
        requests:
          cpu: 1
          memoryInGb: 0.5
      ports:
      - port: 3000
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: '3000'
  imageRegistryCredentials:
    - server: alldaydevops.azurecr.io
      username: REGISTRY_USERNAME
      password: REGISTRY_PASSWORD
tags: null
type: Microsoft.ContainerInstance/containerGroups